local white = Color(255, 255, 255, 255)

killicon.Add("arc9_uplp_ak", "hud/killicons/arc9_uplp_ak", white)
killicon.Add("arc9_uplp_ak12", "hud/killicons/arc9_uplp_ak12", white)
killicon.Add("arc9_uplp_ak_smg", "hud/killicons/arc9_uplp_ak_smg", white)
killicon.Add("arc9_uplp_ar15", "hud/killicons/arc9_uplp_ar15", white)
killicon.Add("arc9_uplp_asval", "hud/killicons/arc9_uplp_asval", white)
killicon.Add("arc9_uplp_aug", "hud/killicons/arc9_uplp_aug", white)
killicon.Add("arc9_uplp_awp", "hud/killicons/arc9_uplp_awp", white)
killicon.Add("arc9_uplp_deagle", "hud/killicons/arc9_uplp_deagle", white)
killicon.Add("arc9_uplp_fal", "hud/killicons/arc9_uplp_fal", white)
killicon.Add("arc9_uplp_fn57", "hud/killicons/arc9_uplp_fn57", white)
killicon.Add("arc9_uplp_knife", "hud/killicons/arc9_uplp_knife", white)
killicon.Add("arc9_uplp_m590", "hud/killicons/arc9_uplp_m590", white)
killicon.Add("arc9_uplp_m9", "hud/killicons/arc9_uplp_m9", white)
killicon.Add("arc9_uplp_m26_thrown", "hud/killicons/arc9_uplp_m26_thrown", white)
killicon.Add("arc9_uplp_mac", "hud/killicons/arc9_uplp_mac", white)
killicon.Add("arc9_uplp_molot", "hud/killicons/arc9_uplp_molot", white)
killicon.Add("arc9_uplp_mp5", "hud/killicons/arc9_uplp_mp5", white)
killicon.Add("arc9_uplp_mp7", "hud/killicons/arc9_uplp_mp7", white)
killicon.Add("arc9_uplp_orsis", "hud/killicons/arc9_uplp_orsis", white)
killicon.Add("arc9_uplp_r870", "hud/killicons/arc9_uplp_r870", white)
killicon.Add("arc9_uplp_scar", "hud/killicons/arc9_uplp_scar", white)
killicon.Add("arc9_uplp_spas", "hud/killicons/arc9_uplp_spas", white)
